Added stats to log message
skyme5/snapchat-dl pull request #17
Opened 2023-06-08 11:09 UTC by Walmann

2023-06-10 08:08 UTC, skyme5 requested changes
@Walmann thanks for raising a PR, I've reviewed your PR and there are few comments which needs to be resolved

2023-06-10 08:08 UTC, skyme5 commented on snapchat_dl/snapchat_dl.py
> +        stories_already_exists = 0
Can we rename `stories_already_exists` -> `story_download_count`

2023-06-10 08:08 UTC, skyme5 commented on snapchat_dl/snapchat_dl.py
> +        stories_downloaded = 0
I think we don't need this, we can simply compute it by doing subtraction `stories.length - story_download_count`

2023-06-10 08:08 UTC, skyme5 commented on snapchat_dl/snapchat_dl.py
> +
`download_url` already handles case when file is downloaded, remove `continue` here and imply increment variable

2023-06-10 08:08 UTC, skyme5 commented on snapchat_dl/snapchat_dl.py
> +                stories_downloaded+=1
remove since we can derive it from `stories.length - story_download_count`

2023-06-10 08:08 UTC, skyme5 commented on snapchat_dl/snapchat_dl.py
> +
@Walmann please format this using `black`

2023-06-12 12:38 UTC, Walmann commented
See new PR.

2023-06-12 12:38 UTC, closed without merging